### ISSUE TITLE
CodersX review

### ISSUE THREAD

**Issue by khoinguyen-corize** [malburo/clocks#1]
- [x] Không hỗ trợ thiết bị di động, cần responsive

- [x] Action delete nên có confirm trước khi xóa

- [x] Số giây nhảy không đồng bộ => F5 lại trang mới đồng bộ

- [x] Cần check nếu đã chọn timezone đó rồi thì k cho chọn nữa, hiện tại có thể chọn được 1 timezone nhiều lần

- [x] Sử dụng font icon thay vì dùng hình ảnh làm icon

- [x] Đổi tên thư mục constants thay vì constant

- [x] Không cần tạo thư mục custom-field, đẩy 2 component đó vào thư mục components là được

- [x] Nên đồng nhất ngôn ngữ, không được dùng tiếng Việt + tiếng Anh kết hợp

**Comment by malburo** [comment]
"Số giây nhảy không đồng bộ => F5 lại trang mới đồng bộ" cái này em ngồi mò mãi mà ko được anh Khôi ơi, anh xem giúp em với

**Comment by malburo** [comment]
Em fix xong rồi anh Khôi ơi, anh xem giúp em còn gì phải thay đổi nữa ko ạ, em cảm ơn !
